"use client";

import React from "react";
import { ArrowRight, Sparkles } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export default function MotionGeneratorHero() {
  return (
    <section
      id="motion-generator-hero"
      className="py-24 relative w-full overflow-hidden bg-slate-950 flex flex-col items-center justify-center px-4 md:px-6"
    >
      {/* Background Gradients */}
      <div className="absolute inset-0 hero-gradient z-10"></div>
      <div className="absolute top-0 left-0 right-0 h-32 bg-gradient-to-b from-slate-950 via-slate-950/50 to-transparent z-20 pointer-events-none"></div>
      <div className="absolute bottom-0 left-0 right-0 h-20 bg-gradient-to-t from-slate-950 to-transparent z-20"></div>

      {/* 🌟 HEADER TEXT 🌟 */}
      <div className="flex flex-col items-center text-center z-30 mb-10 max-w-2xl mx-auto">
        <span className="mb-4 inline-flex items-center gap-2 border border-teal-400/30 text-teal-400 px-3 py-1 text-sm rounded-md bg-teal-500/10">
          <Sparkles className="w-4 h-4" /> AI Motion Graphics
        </span>
        <h2 className="text-3xl md:text-5xl font-bold mb-4 text-white leading-tight">
          Free AI{" "}
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-teal-400 to-cyan-400">
            Motion Generator.
          </span>
        </h2>
        <p className="text-gray-400 text-lg mb-6 max-w-lg mx-auto">
          100% Free forever. Turn text into beautiful Motion graphics.
        </p>
      </div>

      {/* 🌟 16:9 LANDSCAPE VIDEO PLAYER 🌟 */}
      <div className="relative w-full max-w-3xl aspect-video rounded-2xl md:rounded-3xl overflow-hidden border border-white/10 shadow-[0_0_50px_rgba(20,184,166,0.15)] bg-black z-30 ring-1 ring-white/5">
        <video
          src="/tools/motions.webm"
          autoPlay
          loop
          muted
          playsInline
          className="absolute inset-0 w-full h-full object-cover"
        />

        {/* Top "Generated by AI" Badge floating over the video */}
        <div className="absolute top-4 left-4 bg-teal-500/90 backdrop-blur-sm text-black text-[10px] md:text-xs font-black px-3 py-1 rounded-full shadow-lg uppercase tracking-widest">
          Generated by AI
        </div>
      </div>

      {/* Call to Action */}
      <div className="text-center mt-12 z-30">
        <Link href="/dashboard/video/motions">
          <Button className="h-12 bg-gradient-to-r from-cyan-500 to-teal-500 hover:from-cyan-400 hover:to-teal-400 text-black px-8 rounded-full shadow-[0_0_20px_rgba(20,184,166,0.3)] transition-all hover:scale-105 font-bold text-base">
            Try Motion Generator Free <ArrowRight className="ml-2 h-5 w-5" />
          </Button>
        </Link>
      </div>
    </section>
  );
}
